const modules=[
{n:1,ar:'الإدارة والقيادة',en:'Management & Leadership',lessons:[['فلسفات الجودة','تطورت الجودة من الفحص النهائي إلى ضبط العملية ثم ضمان الجودة وإدارة الجودة الشاملة. ركّز Deming على النظام والتباين والتحسين المستمر، وJuran على التخطيط والضبط والتحسين، وCrosby على المطابقة للمتطلبات وتكلفة عدم المطابقة.'],['الاستراتيجية والأهداف','تُحوّل الرؤية إلى أهداف SMART ومؤشرات مترابطة. من الأدوات: SWOT وHoshin Kanri وBalanced Scorecard. يجب ربط أهداف الجودة بالعميل والمخاطر والنتائج المالية والتشغيلية.'],['الفرق وإدارة التغيير','مراحل الفريق: Forming, Storming, Norming, Performing. استخدم RACI لتوضيح المسؤوليات، وادعم التغيير بالتواصل والتدريب والمشاركة وقياس التبني.'],['العميل والمورد','يُحوّل Voice of Customer إلى CTQ قابلة للقياس. تُدار جودة المورد بالتأهيل والتدقيق ومؤشرات الأداء وخطط التطوير والطوارئ.']]},
{n:2,ar:'نظام الجودة',en:'The Quality System',lessons:[['تصميم نظام إدارة الجودة','الـQMS مجموعة عمليات وسياسات ومسؤوليات وموارد. يُدار بمنهج العمليات: مدخلات، أنشطة، مخرجات، مالك، مخاطر، ضوابط ومؤشرات. الوثيقة تحدد المطلوب والسجل يثبت التنفيذ.'],['التدقيق','التدقيق منهجي ومستقل وموثق. أنواعه System, Process, Product، وقد يكون داخليًا أو على المورد أو من جهة مستقلة. عدم المطابقة الجيد يربط المتطلب بالدليل الموضوعي والفجوة.'],['تكلفة الجودة','نموذج PAF: Prevention، Appraisal، Internal Failure، External Failure. تكلفة ضعف الجودة غالبًا تساوي تكاليف الفشل الداخلي والخارجي.'],['التدريب والثقافة','تقاس فعالية التدريب عبر التعلم والسلوك والنتائج، لا الحضور فقط. ثقافة الجودة تحتاج قيادة وقدوة وشفافية ومؤشرات مفهومة.']]},
{n:3,ar:'تصميم المنتج والعملية والخدمة',en:'Design',lessons:[['التحقق والتصديق','Verification يسأل: هل صممنا المنتج وفق المتطلبات؟ Validation يسأل: هل المنتج مناسب للاستخدام المقصود؟ يجب ضبط تغييرات التصميم وتقييم أثرها.'],['QFD وDFX','QFD يحول صوت العميل إلى خصائص هندسية. DFX يشمل التصميم للتصنيع والتجميع والسلامة والاعتمادية والفحص والبيئة.'],['FMEA','DFMEA لمخاطر التصميم وPFMEA لمخاطر العملية. RPN=Severity×Occurrence×Detection، لكن الشدة العالية لا تُهمل حتى لو كان RPN متوسطًا.'],['الاعتمادية','R(t)=e^(-λt)، وMTBF=1/λ عند معدل فشل ثابت. التوافر A=MTBF/(MTBF+MTTR). في الأنظمة المتسلسلة تضرب الموثوقيات، وفي المتوازية تقل احتمالات الفشل الكلي.'],['GD&T','التفاوتات تحدد الانحراف المقبول، وGD&T يضبط الشكل والاتجاه والموقع والملف والانحراف حول Datums. التفاوت الضيق جدًا يرفع التكلفة.']]},
{n:4,ar:'ضبط المنتج والعملية',en:'Product & Process Control',lessons:[['Control Plan','يربط الخاصية بطريقة القياس وحجم العينة والتكرار والحدود وخطة التصرف، ويجب أن يتسق مع Process Flow وPFMEA.'],['المنتج غير المطابق','التصرفات: Rework، Repair، Use-as-is، Scrap، Return to supplier. يجب العزل والتتبع وتقييم الأثر على الدفعات والعملاء.'],['المعايرة والمترولوجيا','Accuracy قرب القياس من الحقيقة، Precision تقارب القراءات، Bias فرق المتوسط عن المرجع، Stability تغير الأداء مع الزمن. الجهاز خارج المعايرة يتطلب تقييم أثر رجعي.'],['MSA وGage R&R','Repeatability تباين نفس المقيم، Reproducibility تباين المقيمين. أقل من 10% غالبًا جيد، 10–30% قد يُقبل حسب الخطر، وأكثر من 30% غير مناسب عادة.'],['أخذ العينات','AQL يمثل جودة جيدة يريد المنتج قبولها غالبًا، وLTPD يمثل جودة سيئة يريد العميل رفضها. Producer Risk α رفض دفعة جيدة، وConsumer Risk β قبول دفعة سيئة.']]},
{n:5,ar:'التحسين المستمر',en:'Continuous Improvement',lessons:[['أدوات الجودة السبع','Pareto، Fishbone، Check Sheet، Histogram، Scatter، Control Chart، Flowchart/Stratification. الأداة تولد فرضية أو تعرض نمطًا ولا تثبت السبب وحدها.'],['RCA و8D وCAPA','Correction يعالج الحالة الحالية، وCorrective Action يزيل السبب لمنع التكرار. 8D يشمل الفريق والوصف والاحتواء والسبب الجذري والإجراء والتحقق ومنع التكرار.'],['Lean','الهدر TIMWOODS. Takt Time=الوقت المتاح/طلب العميل. OEE=Availability×Performance×Quality. من الأدوات 5S وVSM وKanban وSMED وStandard Work.'],['Six Sigma','DMAIC: Define, Measure, Analyze, Improve, Control. DPMO=العيوب/(الوحدات×فرص العيب)×1,000,000. RTY حاصل ضرب Yield لكل مرحلة.'],['DOE','يدرس العوامل ومستوياتها وتفاعلاتها. المبادئ: Randomization، Replication، Blocking. Full Factorial يختبر كل التركيبات، وFractional يقلل التجارب مع احتمال Confounding.']]},
{n:6,ar:'الطرق الكمية والأدوات',en:'Quantitative Methods',lessons:[['الإحصاء الوصفي','المتوسط والوسيط والمنوال والمدى والتباين والانحراف المعياري. s²=Σ(x-x̄)²/(n-1). معامل الاختلاف CV=s/x̄×100%.'],['الاحتمالات والتوزيعات','Normal للقياسات المستمرة، Binomial للنجاح/الفشل، Poisson لعدد الأحداث، Exponential للزمن بين الأحداث، Weibull للاعتمادية. Z=(x-μ)/σ.'],['اختبار الفرضيات','Type I Error α: رفض H0 وهي صحيحة. Type II Error β: عدم رفض H0 وهي خاطئة. Power=1-β. إذا p≤α نرفض H0، لكن الدلالة الإحصائية لا تعني أهمية عملية.'],['الارتباط والانحدار وANOVA','الارتباط لا يثبت السببية. الانحدار يبني نموذجًا للتنبؤ. ANOVA يقارن عدة متوسطات ويحدد إن كان واحد على الأقل مختلفًا.'],['SPC','X̄-R وX̄-S وI-MR للمتغيرات، وp وnp وc وu للصفات. حدود السيطرة مشتقة من بيانات العملية، وليست حدود مواصفة.'],['قدرة العملية','Cp=(USL-LSL)/(6σ). Cpk=min[(USL-μ)/(3σ),(μ-LSL)/(3σ)]. Cp قدرة محتملة، وCpk يعكس التمركز. يجب أن تكون العملية مستقرة ونظام القياس مناسبًا.']]},
{n:7,ar:'إدارة المخاطر',en:'Risk Management',lessons:[['أساسيات المخاطر','الخطر أثر عدم اليقين على الأهداف. Inherent Risk قبل الضوابط، Residual Risk بعدها. يجب تحديد المالك والاحتمال والأثر والإجراء والمؤشر.'],['أدوات التحليل','FMEA من الأسفل للأعلى، FTA من حدث علوي للأسباب، HAZOP للانحرافات، Bow-Tie للتهديدات والحدث والعواقب والضوابط.'],['المعالجة والاستمرارية','الخيارات: Avoid، Reduce، Transfer/Share، Accept. استمرارية الأعمال تركز على استمرار العمليات الحرجة، وDisaster Recovery على استعادة الأنظمة والبيانات.']]}
];
const qs=[
['أي عبارة صحيحة عن حدود المواصفة؟',['تُحسب دائمًا من بيانات العملية','يحددها العميل أو التصميم','هي نفسها حدود السيطرة','لا تستخدم في القدرة'],1],
['Producer Risk يعني:',['قبول دفعة سيئة','رفض دفعة جيدة','قبول دفعة جيدة','رفض دفعة سيئة'],1],
['تحسين الفحص النهائي في FMEA يؤثر غالبًا على:',['Severity','Occurrence','Detection','لا شيء'],2],
['إذا Cp مرتفع وCpk منخفض فهذا يعني غالبًا:',['العملية متمركزة','العملية غير متمركزة','القياس مثالي','لا توجد مواصفات'],1],
['أي مخطط يناسب نسبة غير المطابق مع تغير حجم العينة؟',['np','p','c','u'],1],
['Type I Error هو:',['عدم رفض H0 وهي خاطئة','رفض H0 وهي صحيحة','انخفاض القوة فقط','قبول H1 دائمًا'],1],
['أي أداة تكشف التفاعلات بين العوامل؟',['Pareto','DOE','Check Sheet','Flowchart'],1],
['Rework يعني:',['إعادة المنتج للمواصفة الأصلية','قبوله كما هو','إتلافه','إصلاح لا يحقق المواصفة'],0],
['ما الفرق بين Verification وValidation؟',['لا فرق','الأول للمواصفات والثاني للاستخدام','الأول للعميل فقط','الثاني يسبق التصميم دائمًا'],1],
['MTBF=900 وMTTR=100، التوافر؟',['10%','50%','90%','100%'],2],
['Reproducibility في MSA ترتبط غالبًا بـ:',['اختلاف القطع','اختلاف المقيمين','حدود المواصفة','القيمة الاسمية'],1],
['أي أداة تبدأ من حدث علوي؟',['FMEA','FTA','QFD','SPC'],1],
['Correction تعني:',['إزالة السبب الجذري','إصلاح الحالة الحالية','منع كل المخاطر','تدقيق النظام'],1],
['RTY يساوي:',['مجموع Yield','حاصل ضرب Yield للمراحل','DPMO فقط','OEE'],1],
['أي عبارة صحيحة عن الارتباط؟',['يثبت السببية','لا يتأثر بالقيم الشاذة','يقيس علاقة ولا يثبت السببية','يعني تطابقًا'],2],
['Cpk يصبح أكثر معنى بعد:',['التأكد من الاستقرار وملاءمة القياس','زيادة الفحص فقط','إلغاء المواصفات','استخدام بيانات وصفية'],0],
['أقوى إجراء لمنع إعداد خاطئ متكرر:',['زيادة الفحص فقط','Poka-Yoke','زيادة التقارير','قبول الخطر'],1],
['أي تكلفة تُعد فشلًا خارجيًا؟',['التدريب','المعايرة','إعادة العمل قبل الشحن','مطالبة ضمان'],3],
['RACI Accountable هو:',['المنفذ','المستشار','المسؤول النهائي','المُبلّغ'],2],
['أي خيار ليس معالجة نظامية للخطر؟',['Avoid','Reduce','Transfer','Ignore بلا قرار'],3]
];
function render(){let h='';modules.forEach(m=>{h+=`<section class="module" id="module-${m.n}"><div class="module-title"><span>المحور ${m.n}</span><h2>${m.ar}</h2><small>${m.en}</small></div>`;m.lessons.forEach((l,i)=>{let id=`m${m.n}-l${i+1}`;h+=`<article class="lesson"><div class="lesson-head"><span>${m.n}.${i+1}</span><h3>${l[0]}</h3></div><div class="lesson-body"><p>${l[1]}</p></div><label class="done"><input type="checkbox" data-progress="${id}"> تمت مذاكرة الدرس</label></article>`});h+='</section>'});document.getElementById('modules').innerHTML=h;initProgress()}
function initProgress(){let b=[...document.querySelectorAll('[data-progress]')];function u(){let n=0;b.forEach(x=>{if(x.checked)n++;localStorage.setItem('cqe-'+x.dataset.progress,x.checked?'1':'0')});let p=Math.round(n/b.length*100);progress.value=p;progressText.textContent='التقدم '+p+'%'}b.forEach(x=>{x.checked=localStorage.getItem('cqe-'+x.dataset.progress)==='1';x.onchange=u});u()}
let active=[];function buildQuiz(n=20){active=[];for(let i=0;i<n;i++)active.push(qs[i%qs.length]);quiz.innerHTML=active.map((x,i)=>`<div class="qcard" id="q${i}"><b>${i+1}. ${x[0]}</b>${x[1].map((o,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${o}</label>`).join('')}<div class="answer">الإجابة الصحيحة: ${x[1][x[2]]}</div></div>`).join('');examMeta.textContent=`عدد الأسئلة: ${n}`;score.textContent=''}
function grade(){let s=0;active.forEach((x,i)=>{let v=document.querySelector(`input[name=q${i}]:checked`),c=document.getElementById('q'+i);c.classList.add('show');if(v&&+v.value===x[2]){s++;c.classList.add('correct')}else c.classList.add('wrong')});score.textContent=`النتيجة: ${s} من ${active.length} (${Math.round(s/active.length*100)}%)`}
document.querySelectorAll('.toc-btn').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.target).scrollIntoView());render();buildQuiz(20);