window.COURSES = [
  {
    id: "six-sigma-green-belt",
    number: "01",
    titleAr: "الحزام الأخضر في ستة سيغما",
    titleEn: "Six Sigma Green Belt",
    shortTitleAr: "Six Sigma Green Belt",
    shortTitleEn: "Six Sigma Green Belt",
    descriptionAr: "دورة متدرجة في منهجية DMAIC، تحليل العمليات، أدوات الجودة، والتفكير الإحصائي لتحسين الأداء واتخاذ القرار.",
    descriptionEn: "A structured course on DMAIC, process analysis, quality tools, and statistical thinking for performance improvement and decision-making.",
    categoryAr: "التحسين المستمر",
    categoryEn: "Continuous Improvement",
    tagsAr: ["DMAIC", "أدوات الجودة", "تحليل العمليات"],
    tagsEn: ["DMAIC", "Quality tools", "Process analysis"],
    languageAr: "عربي / إنجليزي",
    languageEn: "Arabic / English",
    url: "https://eng-abdullah-omar.github.io/six-sigma-course-GR/",
    symbol: "σ",
    accent: "#239775",
    accentSoft: "#e6f4ef",
    accentDark: "#0d5142",
    status: "available"
  },
  {
    id: "iso9001-audit-academy",
    number: "02",
    titleAr: "ISO 9001 المدقق الداخلي والمدقق الرئيسي",
    titleEn: "ISO 9001 Internal & Lead Auditor",
    shortTitleAr: "ISO 9001 Auditor",
    shortTitleEn: "ISO 9001 Auditor",
    descriptionAr: "دورة مفصلة في متطلبات نظام إدارة الجودة ومنهجية التدقيق، تشمل الحالات العملية، صياغة عدم المطابقة، وقيادة فريق التدقيق.",
    descriptionEn: "A detailed course on quality management system requirements and auditing, including practical cases, nonconformity writing, and audit-team leadership.",
    categoryAr: "التدقيق ونظم الجودة",
    categoryEn: "Auditing & Quality Systems",
    tagsAr: ["44 درسًا", "ISO 9001", "Lead Auditor"],
    tagsEn: ["44 lessons", "ISO 9001", "Lead Auditor"],
    languageAr: "عربي / إنجليزي",
    languageEn: "Arabic / English",
    lessons: 44,
    url: "https://eng-abdullah-omar.github.io/iso9001-audit-academy/",
    symbol: "✓",
    accent: "#3f67e8",
    accentSoft: "#e9edff",
    accentDark: "#173179",
    status: "available"
  },
  {
    id: "asq-cqe-preparation",
    number: "03",
    titleAr: "دورة مهندس الجودة المعتمد CQE",
    titleEn: "Certified Quality Engineer CQE Preparation",
    shortTitleAr: "ASQ CQE",
    shortTitleEn: "ASQ CQE",
    descriptionAr: "دورة عربية شاملة للتحضير لاختبار مهندس الجودة المعتمد، تشمل أنظمة الجودة، التصميم، ضبط العمليات، التحسين، الإحصاء وإدارة المخاطر.",
    descriptionEn: "A comprehensive Arabic preparation course covering quality systems, design, process control, improvement, statistics, and risk management.",
    categoryAr: "هندسة الجودة",
    categoryEn: "Quality Engineering",
    tagsAr: ["7 محاور", "32 درسًا", "محاكي 160 سؤالًا"],
    tagsEn: ["7 domains", "32 lessons", "160-question simulator"],
    languageAr: "عربي مع المصطلحات الإنجليزية",
    languageEn: "Arabic with English terminology",
    lessons: 32,
    url: "./cqe/",
    symbol: "Q",
    accent: "#d6a847",
    accentSoft: "#fff6dc",
    accentDark: "#72530e",
    status: "available"
  }
];
